### ISSUE TITLE
Github app to batch clone Github Issues 

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Changes#2]
## I want to do this:

1. Build a Github App that **batch clones** GitHub Issues from a CYF coursework repo to a trainee's coursework repo.

2. Build a React component that queries the coursework repo and shows the issues as assignments.

## Here’s why I want to do it:

1. I want to free us all from the burden of Google Classroom, which drives us all mad
2. I want a single source of truth for coursework assignments so that there's only [one place to make changes](https://github.com/CodeYourFuture/HTML-CSS-Coursework-TEST/issues) instead of ~12
3. I want to use something our volunteers are familiar with already
4. I want to use something more than 20 people can access
5. I want to use something with a [free, functional AP](https://docs.github.com/en/rest/issues?apiVersion=2022-11-28)I we can get useful data from easily
7. I want to use something that empowers our trainees to [plan their time](https://github.com/orgs/CodeYourFuture/projects/41/views/2)
8. I want to use something that [prepares our trainees for Final Projects](https://github.com/orgs/CodeYourFuture/projects/41)
9. I want to use something that our trainees will need to know and use again in their careers
10. I want to use something that will generate [insights from activity data](https://github.com/orgs/CodeYourFuture/projects/41/insights/1) automatically
11. I want to use something public, that isn't hidden away

## Here’s how it serves our goals:

See above. The Github app serves all the listed goals. It is a small, practical bridge between three existing platforms: the syllabus, gihub, and the trainee tracker. 

### already done:
- I have trialled versions of creating coursework tasks as Github issues over the past 5 months
- I have researched the problem, read the API, [written a spec](https://docs.google.com/document/d/1zFx-RscN4Iy9hhLKPm_wZUxsTqPq7CNR4ZZp566b2uI/edit?usp=sharing) and some sample code
- I have asked a contractor to estimate times and prices

### still available
- I can spend 12 hours over the next 10 weeks to deliver this product, including creating the 8 source repos, labelling/editing the coursework, and making some videos for trainees

## This is the help I need from others to get this done (if any):

1. I need a contractor to build the Github App and button
1. I need some juniors to :
- build the React component for the Syllabus
- export all the coursework from boilerplate classroom to a google sheet
- programmatically create issues from a spreadsheet (there are multiple premade scripts to do this as it's a common use case)
- test the kanbans and iterate on them

[SPEC DOC](https://docs.google.com/document/d/1zFx-RscN4Iy9hhLKPm_wZUxsTqPq7CNR4ZZp566b2uI/edit?usp=sharing)

**Comment by SallyMcGrath** [comment]
Updating on this:

We have created:
- Module Template (to populate with coursework per module) https://github.com/CodeYourFuture/Module-Template
- We have completed JS3 using this to work out any kinks https://github.com/CodeYourFuture/Module-JS3/
- We have created an example Coursework Planner repo for trainees to start using manually https://github.com/CodeYourFuture/Coursework-Planner
- Ditto board https://github.com/orgs/CodeYourFuture/projects/82

We will try it for L10/GL6

**Comment by berkeli** [comment]
An update from me: 

Syllabus: 
* Added issues table component (copy+paste from doc) and added the tabel for JS3 module (all 4 weeks)
* Added a page for troubleshooting setup. This is required as students will need to copy the project board manually (copying projectV2 requires us to give api access to the org, and api doesn't support adding/modifying standard columns)
* A bit of refactoring for errors

APP: 
* Updated to use nest.js
* API docs with swagger 
* Tracing with honeycomb
* endpoint to provide issues which uses redis cache (cached for 24hrs). This is using render's free tier, which is more than sufficient.

**Comment by SallyMcGrath** [comment]
Awesome -- please bear in mind that the syllabus front end will probably be replaced in the next few months, so don't tie your button app too closely to the docusaurus front end.

If you have requirements for the front end (eg, React), also state them

**Comment by 40thieves** [comment]
Quick update on this: I reviewed the [original PR](https://github.com/CodeYourFuture/syllabus/pull/633) for the frontend piece, which is looking good. However as Sally mentions above, we are now looking to replace the current version of the Syllabus and move away from Docusaurus / built-in MDX.

This means that the PR will need to be made a bit more generic to work with the new syllabus. We do want to support React components in the new syllabus, so we were thinking that extracting out the underlying components to a separate library would be a viable option. We could then install that into the new syllabus codebase. I’d be happy to help with this and/or review anything!

I'm also attempting to review the code in https://github.com/berkeli/coursework-helper, but to be honest I'm not much of a backend dev and don't have much experience with Nest. But it's an interesting learning experience :)
